// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzql2-DGKcHx1CUDhkkl45360DzVnVxlE',
    appId: '1:914942552899:web:fb71c581fa4af5b17c5df6',
    messagingSenderId: '914942552899',
    projectId: 'crupd-a2d62',
    authDomain: 'crupd-a2d62.firebaseapp.com',
    storageBucket: 'crupd-a2d62.appspot.com',
    measurementId: 'G-5QSKHT1P2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMc1fWnCVCFT-h8zgFy6t0C-LVwc5rvQA',
    appId: '1:914942552899:android:aeb2591e1bb9672c7c5df6',
    messagingSenderId: '914942552899',
    projectId: 'crupd-a2d62',
    storageBucket: 'crupd-a2d62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAyBuFcSe7iYU1Sk41Dah36ttD86TXngM',
    appId: '1:914942552899:ios:81f5bc92842cd0667c5df6',
    messagingSenderId: '914942552899',
    projectId: 'crupd-a2d62',
    storageBucket: 'crupd-a2d62.appspot.com',
    iosBundleId: 'com.example.crupd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAyBuFcSe7iYU1Sk41Dah36ttD86TXngM',
    appId: '1:914942552899:ios:3d9a0ebcdd4d223a7c5df6',
    messagingSenderId: '914942552899',
    projectId: 'crupd-a2d62',
    storageBucket: 'crupd-a2d62.appspot.com',
    iosBundleId: 'com.example.crupd.RunnerTests',
  );
}
